# Generated by Django 3.2.14 on 2023-03-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(help_text='Максимум 350 символов', max_length=350, verbose_name='Description'),
        ),
    ]
