# Generated by Django 3.2.14 on 2023-03-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='header_h1',
        ),
    ]
