# Generated by Django 3.2.14 on 2023-03-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_article_header_h1'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineprice',
            name='pd_change_num',
            field=models.FloatField(blank=True, help_text='Автообновление каждые 30 минут', null=True, verbose_name='Изменение Pd (число)'),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='pt_change_num',
            field=models.FloatField(blank=True, help_text='Автообновление каждые 30 минут', null=True, verbose_name='Изменение Pt (число)'),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='rh_change_num',
            field=models.FloatField(blank=True, help_text='Автообновление каждые 30 минут', null=True, verbose_name='Изменение Rh (число)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pd_change',
            field=models.FloatField(blank=True, help_text='Автообновление каждые 30 минут', null=True, verbose_name='Изменение Pd (процент)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pt_change',
            field=models.FloatField(blank=True, help_text='Автообновление каждые 30 минут', null=True, verbose_name='Изменение Pt (процент)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='rh_change',
            field=models.FloatField(blank=True, help_text='Автообновление каждые 30 минут', null=True, verbose_name='Изменение Rh (процент)'),
        ),
    ]
