# Generated by Django 3.2.14 on 2023-03-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230310_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixprice',
            options={'verbose_name': 'Биржа - фиксы', 'verbose_name_plural': 'Биржа - фиксы'},
        ),
        migrations.AlterModelOptions(
            name='onlineprice',
            options={'verbose_name': 'Биржа - online котировки', 'verbose_name_plural': 'Биржа - online котировки'},
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_1_rh_rub_am',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_1_rh_rub_pm',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_1_rh_usd_am',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_1_rh_usd_pm',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_2_rh_rub_am',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_2_rh_rub_pm',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_2_rh_usd_am',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_2_rh_usd_pm',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_today_rh_rub_am',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_today_rh_rub_pm',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_today_rh_usd_am',
        ),
        migrations.RemoveField(
            model_name='fixprice',
            name='fix_today_rh_usd_pm',
        ),
    ]
