# Generated by Django 3.2.14 on 2023-03-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230311_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmaterialpagehome',
            name='material_css',
            field=models.CharField(blank=True, help_text='Максимум 20 символов', max_length=20, verbose_name='Класс CSS'),
        ),
    ]
