# Generated by Django 3.2.14 on 2023-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blockmaterialpagehome_material_css'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockguaranteespagehome',
            options={'verbose_name': 'гарантию', 'verbose_name_plural': 'Главная - гарантии'},
        ),
        migrations.AddField(
            model_name='blockguaranteespagehome',
            name='guarantees_css',
            field=models.CharField(blank=True, help_text='Максимум 25 символов', max_length=25, verbose_name='Класс CSS для иконки'),
        ),
    ]
