# Generated by Django 3.2.14 on 2023-03-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230311_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockfaqpagehome',
            options={'verbose_name': 'ответ на вопрос', 'verbose_name_plural': 'Главная - FAQ'},
        ),
        migrations.AlterModelOptions(
            name='blocklistcatalystspagehome',
            options={'verbose_name': 'марку авто', 'verbose_name_plural': 'Главная - марки авто'},
        ),
        migrations.AlterModelOptions(
            name='blockprocesspagehome',
            options={'verbose_name': 'процесс', 'verbose_name_plural': 'Главная - процесс'},
        ),
        migrations.AlterModelOptions(
            name='blockreviewspagehome',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'Главная - отзывы'},
        ),
        migrations.AddField(
            model_name='blocklistcatalystspagehome',
            name='list_alt_image',
            field=models.CharField(blank=True, help_text='Максимум 50 символов', max_length=20, verbose_name='Тег alt для логотипа'),
        ),
        migrations.AlterField(
            model_name='blocklistcatalystspagehome',
            name='list_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ссылка на страницу марки'),
        ),
    ]
