# Generated by Django 3.2.14 on 2023-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230312_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockprocesspagehome',
            name='process_css',
            field=models.CharField(blank=True, help_text='Например work__img-1,2,3 и т.д.', max_length=20, verbose_name='Класс CSS'),
        ),
    ]
