# Generated by Django 3.2.14 on 2023-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_blockprocesspagehome_process_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockprocesspagehome',
            name='process_image',
            field=models.ImageField(blank=True, upload_to='media/home/process', verbose_name='Изображение процесса'),
        ),
    ]
