# Generated by Django 3.2.14 on 2023-03-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_blockprocesspagehome_process_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockprocesspagehome',
            options={'ordering': ['id'], 'verbose_name': 'процесс', 'verbose_name_plural': 'Главная - процесс'},
        ),
        migrations.AddField(
            model_name='modelauto',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.brandauto'),
        ),
        migrations.AlterField(
            model_name='catalysts',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='media/catalog', verbose_name='Фото катализатора 1'),
        ),
        migrations.AlterField(
            model_name='catalysts',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='media/catalog', verbose_name='Фото катализатора 2'),
        ),
        migrations.AlterField(
            model_name='catalysts',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='media/catalog', verbose_name='Фото катализатора 3'),
        ),
        migrations.AlterField(
            model_name='catalysts',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='media/catalog', verbose_name='Фото катализатора 4'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pd_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение Pd (процент)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pd_change_num',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение Pd (число)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pd_price_ask',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Цена Pd Ask USD ounce'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pd_price_bid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Цена Pd Bid USD ounce'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pt_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение Pt (процент)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pt_change_num',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение Pt (число)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pt_price_ask',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Цена Pt Ask USD ounce'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='pt_price_bid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Цена Pt Bid USD ounce'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='rh_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение Rh (процент)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='rh_change_num',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение Rh (число)'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='rh_price_ask',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Цена Rh Ask USD ounce'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='rh_price_bid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Цена Rh Bid USD ounce'),
        ),
        migrations.AlterField(
            model_name='onlineprice',
            name='update',
            field=models.TimeField(blank=True, verbose_name='Время обновления'),
        ),
    ]
