# Generated by Django 3.2.14 on 2023-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20230314_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalysts',
            name='chart_price',
            field=models.TextField(blank=True, help_text='Не редактировать', max_length=3000, verbose_name='Код графика изменения цены'),
        ),
        migrations.AlterField(
            model_name='catalysts',
            name='content',
            field=models.TextField(blank=True, help_text='Максимум 3000 символов', max_length=3000, verbose_name='Описание катализатора'),
        ),
    ]
