# Generated by Django 3.2.14 on 2023-03-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230314_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalysts',
            name='weight',
            field=models.FloatField(blank=True, help_text='Указывать в граммах', null=True, verbose_name='Вес катализатора'),
        ),
    ]
