# Generated by Django 3.2.14 on 2023-03-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_catalysts_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalysts',
            name='update',
            field=models.ForeignKey(blank=True, help_text='Автообновление', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.fixprice', verbose_name='Дата обновления'),
        ),
    ]
