# Generated by Django 3.2.14 on 2023-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_catalysts_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalysts',
            name='quantity_pd',
            field=models.FloatField(blank=True, help_text='Указывать в граммах', null=True, verbose_name='Содержание палладия'),
        ),
        migrations.AlterField(
            model_name='catalysts',
            name='quantity_pt',
            field=models.FloatField(blank=True, help_text='Указывать в граммах', null=True, verbose_name='Содержание платины'),
        ),
        migrations.AlterField(
            model_name='catalysts',
            name='quantity_rh',
            field=models.FloatField(blank=True, help_text='Указывать в граммах', null=True, verbose_name='Содержание родия'),
        ),
    ]
