# Generated by Django 3.2.14 on 2023-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20230314_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalysts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Автообновление раз в сутки', max_digits=10, null=True, verbose_name='Цена катализатора на сегодня'),
        ),
    ]
