# Generated by Django 4.1.7 on 2023-03-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_catalysts_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelauto',
            options={'verbose_name': 'Модели', 'verbose_name_plural': 'Модели'},
        ),
    ]
