# Generated by Django 4.1.7 on 2023-03-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_modelauto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelauto',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.brandauto'),
        ),
    ]
