# Generated by Django 4.1.7 on 2023-03-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_modelauto_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandauto',
            options={'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэнды'},
        ),
    ]
